name: Start Forex Gold Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # 安装Chrome浏览器
        sudo apt-get update
        sudo apt-get install -y chromium-browser
    
    - name: Run the service
      run: |
        python forex_gold_scheduler.py &
        # 注意：在GitHub Actions中运行长期服务需要特殊配置，此为演示
      env:
        PYTHONUNBUFFERED: 1
